title: Searching for Signals - Luke Nathaniel
email: me@lukenathaniel.com
description: >
  A collection of ideas, inspiration, questions and the occasional film reference.
baseurl: ""
url: "http://lukenathaniel.com"
twitter_username: mrlukenathaniel
github_username: developerluke
markdown: kramdown
author:
  name: "Luke Nathaniel"
  email: me@lukenathaniel.com
encoding: utf-8
timezone: America/Chicago
permalink: :year/:month/:day/:title.html
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - LICENSE.txt

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: lukenathaniel.com
  subtitle: Searching for Signals
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
